---
title: "Untitled"
output: html_document
date: "2022-06-08"
---

```{r}
library(sparklyr)
conf <- spark_config_kubernetes(
  master = "k8s://https://34.123.104.67", # Type kubectl cluster-info to get this url.
  version = "3.2",
  image = "gloryvine/spark:3.2.1",
  driver = "sparklyr",
  account = "spark",
  jars = "local:///opt/sparklyr",
  executors = 10
)
conf$spark.driver.cores	<- 4
conf$spark.driver.memory <- "16g"
```

```{r}
sc <- spark_connect(
  config = conf,
  spark_home = "/home/ubuntu/downloads/spark-3.2.1-bin-hadoop3.2"
)
```

```{r}
connection_is_open(sc)
```

```{r}
spark_web(sc)
```


```{r}
tbl_mtcars <- copy_to(sc, mtcars, "spark_mtcars")
```

```{r}
partitions <- tbl_mtcars %>%
  select(mpg, wt, cyl) %>% 
  sdf_random_split(training = 0.5, test = 0.5, seed = 1099)
```

```{r}
fit <- partitions$training %>%
  ml_linear_regression(mpg ~ .)

fit
```

```{r}
summary(fit)
```

```{r}
spark_disconnect(sc)
```

```{r}
system2("pkill", "kubectl") # Cancel port forward.
system2("kubectl", "delete", "pods", "--all") # Delete all pods.
```
